### ISSUE TITLE
Obtain refresh token

### ISSUE THREAD

**Issue by DanielKaufman** [jesperfj/force-rest-api#29]
Hi, 

I have been using [this tutorial](https://developer.salesforce.com/page/Integrating_Java_Spring_Apps_on_Heroku_with_Force.com_REST_APIs) 

And I couldn't obtain the refresh token nor the authorization code... 
How can I get them?

**Comment by jesperfj** [comment]
I am not familiar with the tutorial. Does it use force-rest-api?

**Comment by jesperfj** [comment]
I see that it uses force-rest-api 0.0.19. Not sure what the exact problem is. That demo project hasn't had a commit in 4 years, so it's probably stale.

If you're looking for an example of how to use force-rest-api, perhaps take a look in this repo. The README has a few examples and also look at the tests. It'll probably also help to switch to the lastest version. One of the more recent changes I made was to move it to maven central so you don't need the additional repository in your pom.xml.

I am going to close this. Plz reopen or refile if you're having issues based on the content in this repo. If you want help specifically on the tutorial app, try pinging @jamesward in github or twitter.
