### ISSUE TITLE
why don't you add the query all?

### ISSUE THREAD

**Issue by marcusx2** [jesperfj/force-rest-api#31]
[QueryAll](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_queryall.htm)
At ForceApi.java:
`public QueryResult<Map> queryAll(String query) {
        return queryAll(query, Map.class);
    }`

    `public <T> QueryResult<T> queryAll(String query, Class<T> clazz) {
        try {
            return queryAny(uriBase() + "/queryAll/?q=" + URLEncoder.encode(query, "UTF-8"), clazz);
        } catch (UnsupportedEncodingException e) {
            throw new ResourceException(e);
        }
    }`

**Comment by jesperfj** [comment]
Good idea. Would you be up for adding it to a PR along with a test? If not, I'll try to get to it at some point soon.

**Comment by marcusx2** [comment]
I won't do that, sorry.

**Comment by jesperfj** [comment]
Fixed in force-rest-api-0.0.31
