### ISSUE TITLE
ForceApi with autorenew enabled can/will create new ApiSession but does not provide access to it

### ISSUE THREAD

**Issue by kevflood** [jesperfj/force-rest-api#33]
I had a situation where I was persisting an accessToken and refreshToken to database after doing an oauth login. The initial accessToken provided quickly expires (hour or so) and so internally the autorenew was fetching a new accessToken but I had no way of accessing it. Every time thereafter I would still instantiate ForceApi using the old, invalid access token and good refresh token and every single time ForceApi would then need to use the refreshToken to create a new accessToken. 

This actually caused a further problem in my case because when forceApi was able to communicate I assumed my access token was good and was then using it in my own custom query request (i.e. a url endpoint not supported by this great api - btw, it is great; thanks for the good work). 

Something like this should do it:

`
    /**
     * Need access to ApiSession in case autorenew has been used and a new accessToken issued.
     * That accessToken may be used externally or used for future creation of ForceApi objects.
     * @return current ApiSession in use
     */
    public ApiSession getApiSession(){
        return this.session;
    }
`

**Comment by jesperfj** [comment]
I am chewing on this for a bit. Not especially opposed to it, but I think there is a missing authentication option based on just refreshtoken, client id and client secret. Will get back on this issue once I've had some time to look at it.

**Comment by kevflood** [comment]
Yeah, I agree it would be cleaner to have auth with just refreshToken and clientId+clientSecret but I'm not sure you should hide away the existence of the underlying access token for two reasons: 

1) I imagine a quite common usecase would be that an apiSession needed to be created several times during the natural lifetime of the access token e.g. say a user of your logs in and out several times in an hour. I think in this case you'd have problems: the request token will be used unnecessarily which can result in the refreshToken being invalidated. See [here ](http://salesforce.stackexchange.com/questions/65590/what-causes-a-connected-apps-refresh-token-to-expire)for more info. 
2) a user of the lib may want to use the access token in a custom query. Not having the access to the accessToken I think would needlessly hinder the usefulness of this lib.

Although, maybe the auth option you're looking for is also the one mentioned in a comment in above link: [ JWT Bearer Token flow](https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com#Obtaining_an_Access_Token_using_a_JWT_Bearer_Token) and see [also](https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm&language=en_US). The guy there says it gives more predictable behaviour.

**Comment by jesperfj** [comment]
Ok. Good thoughts.

The original idea behind the design was that you'd hold on to ApiSession and instantiate ForceApi as needed. For example in the multi-user case, ApiSession could be reinstantiated based on a cookie, combined with ApiConfig (which is global) and then a new ForceApi instance is created on every request. ForceApi is cheap to instantiate for that reason.

But there are probably flaws in this at this moment. E.g. it would be nice for the web processing code to know if the access token was refreshed at any point so it can decide to update the cookie.

Anyways, perhaps the original design was speculative and I would like to revisit it now that the library has baked for some years.

As for your links, I don't think the library currently prevents you from avoiding the refresh token revocation issue. But I could be wrong.

As for the JWT Bearer Token flow, I really need to implement support for that. It will open up for more use cases. But I think both methods are equally predictable when used correctly.

I am hoping to find some time to work through this very soon.

**Comment by jesperfj** [comment]
Actually, I originally did not expect the use of refresh tokens in the case of multi-user web apps. In those cases the access token should stay fresh as long as the user is active (and the API is accessed). This is the most safe approach because you don't have to store sensitive refresh tokens anywhere.

**Comment by kevflood** [comment]
> As for your links, I don't think the library currently prevents you from avoiding the refresh token revocation issue. But I could be wrong.

You're right, it doesn't. When it tries to use an accessToken that has expired the library does successfully use the refreshToken to fetch a new accessToken which is great. The issue is that this happens internally in the library so my code cannot know that the access token has been updated.

> Actually, I originally did not expect the use of refresh tokens in the case of multi-user web apps. In those cases the access token should stay fresh as long as the user is active (and the API is accessed). This is the most safe approach because you don't have to store sensitive refresh tokens anywhere.

Apologies, I wasn't clear and I think we may have our wires crossed. The number of users has no bearing on the use-case: each user will have one salesforce account and one account in my system so it is straightforward in that sense.  I will then store an accessToken and a refreshToken for him so that he can schedule the importing of data from salesforce every hour, day, week, or month.

In the use-case I mentioned in comment no. 3, I was referring to your comment "I think there is a missing authentication option based on just refreshtoken" and I just meant that I don't think it would be a good idea to hide the existence of the accessToken completely since using that should be your first port-of-call (and, as you say, the instantiation of the ForceApi is cheap) whereas to re-issue a new accessToken via the refreshToken is not cheap or fast -nor is it recommended.

So, for that reason, if the library does use the refreshToken to get a new accessToken it would be good if I could know about that so then I can then update the accessToken in my cookie/db/persistence.

**Comment by jesperfj** [comment]
Ok. Makes sense. ForceApi is currently intended to be a pure logic class with no state. The state is in ApiSession and ApiConfig. During refresh, ForceApi does mutate ApiSession. So perhaps the right implementation is that you register a callback if you care about this mutation. Would that work for you?

**Comment by kevflood** [comment]
Yes, that sounds good.

**Comment by jesperfj** [comment]
I took a stab at this in #36. Let me know what you think @kevflood.

**Comment by kevflood** [comment]
Looks good to me, Jesper. As you pointed out, the callback maintains the statelessness of ForceAPI. The change is also optional/non-intrusive, backwards-compatible and works.

Many thanks

**Comment by jesperfj** [comment]
I am ending up also adding a `getSession()` method. I think in some cases it will be more useful than the listener and I don't feel like it breaks the idea that ForceApi is stateless. Maybe I am just subtly shifting my point of view on this :-).

**Comment by jesperfj** [comment]
Released in 0.0.36.

**Comment by kevflood** [comment]
Took v0.0.37 and implemented solution in my code using the getSession() method. Yes, although I could have achieved the same thing with the listener it was simpler to do it with the getSession(). I can check if I need to update the session value in a more linear and predictable fashion.

Excellent.  Thanks again

**Comment by jesperfj** [comment]
Thanks for the feedback!
