### ISSUE TITLE
ApiVersion enum does not contain new Versions

### ISSUE THREAD

**Issue by cswendrowski** [jesperfj/force-rest-api#35]
Salesforce added v38.0 in the Winter '17 release and v39.0 in the Spring '17.

I have tested locally that adding these options to the `ApiVersion` enum seems to be the only action required to enable interaction with these releases and have had no issues taking advantage of new API features.

Due to the fairly high rate of version updates (3 times a year) as well as the consistency of versioning, it might be worth adding logic that calculates out the version number based on an input of `[WINTER, SPRING, SUMMER], YEAR` to reduce maintenance, with the calculations as follows:

```
Winter: 3(YEAR - 2004) - 1
Spring: 3(YEAR - 2004)
Summer: 3(YEAR - 2004) + 1
```

An input of `WINTER, 2017` would, therefore, return version 38.

**Comment by jesperfj** [comment]
Good idea with an automatic resolver.

**Comment by jesperfj** [comment]
Spring 2017, v39 isn't completely rolled out yet. I may hold off updating until it's fully rolled out so I can set default to v39.

**Comment by cswendrowski** [comment]
@jesperfj If you wanted to get super fancy about it, you could check against the list of valid Versions in the current Org and throw an error if the library calls an invalid one. This could additionally be used to select the default Version by picking the highest-available: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_versions.htm

Storing the highest available version on initial object creation and then checking against that value should make that a low-cost check

**Comment by jesperfj** [comment]
Yeah. I think that was the design I had in mind before you suggested calculating the version number.

**Comment by jesperfj** [comment]
FYI, in case you didn't notice, you can [set the API version as a string](https://github.com/jesperfj/force-rest-api/blob/master/src/main/java/com/force/api/ApiConfig.java#L63), to avoid being blocked on missing API versions in the enum.

**Comment by jesperfj** [comment]
@cswendrowski 0.033 contains API versions v38 and v39. I still didn't get around to implementing the automatic version handling.

**Comment by jesperfj** [comment]
@cswendrowski I guess I am still on the fence about having it detect version automatically because it creates a small risk that an app will break one day without any code changes being made. There's something comforting about the API version used not changing unless you change your code or update the force-rest-api version number.

I could still implement a utility that allows you to discover the latest / all versions. Again, I probably would resist the temptation to implement something like `ApiVersion.alwaysUseLatest()` since that will tempt users to expose themselves to the problem described above.

**Comment by jesperfj** [comment]
I added a blurb to the readme about setting API version. I don't think I am going to do much more than that. Closing this issue.

**Comment by cswendrowski** [comment]
@jesperfj My company had a few use cases that lead me to work on the ideas that we discussed, such as checking to see if a certain Version was supported in an org so we could write logic based on features we knew to exist only in certain Versions.

I have split my work into two discrete PR's if you are interested in what we have done, and I attempted to take all of your considerations into account when adding these features in hopes that you may find these features useful.

You can find the PR's here:
https://github.com/jesperfj/force-rest-api/pull/38
https://github.com/jesperfj/force-rest-api/pull/39

The only note I have is that in PR 39 I put the Version checking into the ForceApi class both to benefit from the existing Json mapping and HTTP classes as well as to make it very difficult to accidently use the LatestVersion to construct a Config. A developer would have to go out of their way to do so, but it could be done by creating a ForceApi class with a Config, then resetting the Config version with the newest value.
