### ISSUE TITLE
Jodatime Serialization

### ISSUE THREAD

**Issue by bcallender** [jesperfj/force-rest-api#45]
Would it be possible to allow ApiConfig to add serialization mappers to the static instance of Jackson's ObjectMapper use in ForceApi? Or even better, could we pass in our own ObjectMapper so we can customize serialization? My use case is that I use JodaTime DateTime objects, which won't serialize properly to the Salesforce format unless I can configure Jackson to use the JodaModule.

If this is something you're interested in doing, I can whip up a PR

**Comment by jesperfj** [comment]
Thanks for the suggestion.

Is it worth considering supporting JodaTime explicitly (with a toggle or auto-detected if possible)? I'd like to keep the library as simple as possible in terms of surface area.

But I admit I haven't thought deeply about this. Do you have a code sample of how you want it to work ideally?

**Comment by jesperfj** [comment]
Hm. I guess JodaTime is discouraged after JDK 8 which has already been out there for a while now. Then it should probably not be explicitly supported.

My concern with opening up for customizing objectmappers and such is that it makes it harder to evolve this library with backwards compatibility in the future.

**Comment by bcallender** [comment]
That makes sense -- I've migrated my project over to the Java built in objects since I can use Java 8. It is worth noting though that a lot of people using Salesforce are enterprise and may be limited to Java 7 though. 

I think you still need to install the [Jackson modules for Java 8](https://github.com/FasterXML/jackson-modules-java8) if you want to support Java 8's LocalDateTime and ZonedDateTime serialization/deserialization.

**Comment by jesperfj** [comment]
Ok. I'll look into Jackson config when I find some time (if you don't beat
me to it).

I won't worry about developers being stuck on 7 until I hear complaints
:-).

**Comment by madorb** [comment]
I'm running into this same issue as well. I think that it's fairly standard practice to expose the JSON Serializers for external configuration - joda time is just one of many reasons that folks may want t configure that serialization. And for better or worse, a LOT of large enterprises (which have a fairly high likelihood to also be using salesforce) are still on older versions of java. I'm working for a large financial company atm and i'm limited to Java 7.

**Comment by jesperfj** [comment]
@madorb Take a look at #51 and see if this would work for you. Specifically look at [JodaTimeSample](https://github.com/jesperfj/force-rest-api/blob/custom-object-mapper/src/test/java/com/force/api/JodaTimeSample.java)

**Comment by jesperfj** [comment]
@madorb @bcallender check out release 0.0.38. You can set a custom ObjectMapper on ApiConfig now.

**Comment by jesperfj** [comment]
I'll close this issue for now. Feel free to reopen if 0.0.38 does not address your needs.
