### ISSUE TITLE
Possibility to reconfigure the json mapper?

### ISSUE THREAD

**Issue by bb-scout24** [jesperfj/force-rest-api#48]
Hi,

The following line in the `ForceApi` class is causing us some trouble:
`jsonMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);`

https://github.com/jesperfj/force-rest-api/blob/8b64d0fb46d817b7f1e4d6071d9b5653058f0b8b/src/main/java/com/force/api/ForceApi.java#L50

The problem we are having is that when an attribute currently has a value, but then that value was cleared, we receive that new value as "null" from our source system, but it never reaches Salesforce because this null value is ignored by the JSON serialization in ForceApi.

Was there a specific reason why this is the non-changeable default? Would it maybe be a good extension to make this configurable?

We'd be happy to create a pull request for this, were just wondering what the best way might be. Would it be too granular to introduce a boolean option in the configuration that says `includeNonNull`, with default value `true`? (In that case the jsonMapper couldn't be a static field anymore, would have to be an instance field that gets initialised in the constructor)

Thanks!

**Comment by jesperfj** [comment]
Can you provide a test that demonstrates the behavior you'd like? That'll be the fastest way for me to wrap my head around this.

**Comment by jesperfj** [comment]
It would be lovely if you can take a look at my proposed changes in #51. This will allow you to use a custom object mapper of your choice. It was primarily designed to fix #45, but it might also help you. However, I really am not sure what will work for erasing field values. I haven't paid attention to that recently.

**Comment by bb-scout24** [comment]
It seems like #51 would solve our issue, yes! Perfect.
In that case you can ignore our pull request :-)

Any plans when you are going to release 0.0.38?

**Comment by jesperfj** [comment]
0.0.38 has been released. Please check it out and let me know if things are working as expected.
