### ISSUE TITLE
Timeouts are not handled

### ISSUE THREAD

**Issue by bb-scout24** [jesperfj/force-rest-api#52]
In our application, we started seeing requests to Salesforce time out, which led to problems with blocked threads and our application basically "hanging" after a while.

Digging into the code, it looks as if there is no explicit timeout set with the HTTP clients used. For now, we fixed out problem by wrapping the call into a Hystrix command (which then indeed showed that our problem was timeouts). We just wanted to raise this problem here, as others might run into it as well. Maybe it would be a good extension to allow users to configure a timeout for the calls?

**Comment by montague** [comment]
We're hitting this problem as well. Would you accept a PR for adding a configurable timeout? If so, I'll dig in.

**Comment by holtonma** [comment]
Likewise, hitting this too.  Would be ideal to be able to pass in timeout for `connection` and `read`.  Perhaps default could be the Salesforce imposed limit instead of 0/infinity.

**Comment by montague** [comment]
@jesperfj great, i'll start looking at this.

**Comment by jesperfj** [comment]
@bb-scout24 @montague request timeout is now available in 0.0.40 thanks to contribution from @montague !
