### ISSUE TITLE
How to generate Jackson object from wsdl?

### ISSUE THREAD

**Issue by janu019** [jesperfj/force-rest-api#63]
You have mentioned that, we need to have Objects with proper Jackson deserialization annotations, How can we create jaxb/jackson object from the enterprise wsdl.

When i use wsc jar [https://github.com/forcedotcom/wsc] to generate the objects, the objects are totally different (soap related). Writing all these objects will be a huge task - is there any best solution to generate these like the way you have mentioned.

 

Here is the code you have mentioned.
This assumes you have an Account class defined with proper Jackson deserialization annotations. For example:
@JsonIgnoreProperties(ignoreUnknown=true)
public class Account {
}

**Comment by jesperfj** [comment]
You're right that writing such objects is a big task. But it's still far simpler than what's going on with SOAP/WSDL. For example, you'd generally write classes that omit properties/fields that you're not using. I explicitly kept it out of scope of this library to do class generation. You may be able to find this elsewhere on the Interwebs.

**Comment by janu019** [comment]
Thanks for the quick reply @jesperfj, I will keep exploring otherwise will use xjc and clean the generated files. I am surprised that Salesforce does not give the library or proper xsd.
