### ISSUE TITLE
Provide support for Rest Resource calls.

### ISSUE THREAD

**Issue by ModeratelyComfortableChair** [jesperfj/force-rest-api#86]
Love the library. Would just be great if you could allow for Rest Resource calls. The ForceApi.uriBase() gets in the way of targeting /services/apexrest. If we could either get a request function which doesn't add this to the .url, or make the fields protected so we could extend the class and overwrite our function, it would be awesome! I'm currently just copying over the entire class, but that doesn't look as neat.

**Comment by jesperfj** [comment]
This is now supported in v0.0.44
