### ISSUE TITLE
Is support search api now?

### ISSUE THREAD

**Issue by EINDEX** [jesperfj/force-rest-api#91]
I saw in the wiki, there have one Spec include the search function, but in code didn't found this.

**Comment by jesperfj** [comment]
Can you add a link to what you are referring to?

**Comment by EINDEX** [comment]
Sure, 
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_search.htm
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_search_parameterized.htm
Those two api from salesforce.

**Comment by EINDEX** [comment]
Hi, I create a PR for this, cloud you please check it.

**Comment by jesperfj** [comment]
Thank you. Will take a look.
